//! Build script for gpui_aros.
//!
//! The C glue (`c/gpui_aros_glue.c`) wraps AROS Intuition/CyberGraphics. It is
//! only compiled when targeting AROS *and* the AROS SDK proto headers are
//! present. Those headers live in the canonical build tree at
//! `/tmp/arosbuild/...`; they are generated by the OS build and get GC'd
//! between sessions. When they are absent we skip the cc invocation so that a
//! plain `cargo check` still succeeds — the final runnable AROS binary links
//! the glue object via collect-aros at link time (like hosted/feraille).
use std::env;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=c/gpui_aros_glue.c");

    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    if target_os != "aros" {
        return;
    }

    // The headers the glue needs, produced by the AROS OS build. Probe every
    // include root the glue reaches (proto/, exec/, devices/, …) — the /tmp
    // tree gets GC'd piecemeal, so a single surviving file (it happens:
    // proto/exec.h outlived exec/types.h once) must not trick us into a
    // doomed cc invocation.
    let include_root = "/tmp/arosbuild/bin/darwin-aarch64/gen/include";
    let probes = [
        "proto/exec.h",
        "proto/intuition.h",
        "proto/cybergraphics.h",
        "proto/keymap.h",
        "exec/types.h",
        "devices/inputevent.h",
        "intuition/intuition.h",
        "cybergraphx/cybergraphics.h",
    ];
    if let Some(missing) = probes
        .iter()
        .find(|p| !Path::new(include_root).join(p).exists())
    {
        println!(
            "cargo:warning=gpui_aros glue deferred to link time (SDK header {missing} absent)"
        );
        return;
    }

    // CC / CFLAGS come from the workspace .cargo/config.toml (host clang, ELF
    // triple, large code model, x18 reserved, AROS SDK include paths).
    // -Wno-pointer-sign matches the AROS C convention (STRPTR is unsigned
    // char*; string literals are plain char*) — same flag the hosted/rust
    // build scripts pass.
    cc::Build::new()
        .file("c/gpui_aros_glue.c")
        .flag("-Wno-pointer-sign")
        .compile("gpui_aros_glue");
}
