//! Build script for gpui_aros.
//!
//! The C glue (`c/gpui_aros_glue.c`) wraps AROS Intuition/CyberGraphics. It is
//! only compiled when targeting AROS *and* the AROS SDK proto headers are
//! present. Those headers live in the canonical build tree at
//! `/tmp/arosbuild/...`; they are generated by the OS build and get GC'd
//! between sessions. When they are absent we skip the cc invocation so that a
//! plain `cargo check` still succeeds — the final runnable AROS binary links
//! the glue object via collect-aros at link time (like hosted/feraille).
use std::env;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=c/gpui_aros_glue.c");

    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    if target_os != "aros" {
        return;
    }

    // The proto headers the glue needs, produced by the AROS OS build.
    let proto_probe = "/tmp/arosbuild/bin/darwin-aarch64/gen/include/proto/exec.h";
    if !Path::new(proto_probe).exists() {
        println!(
            "cargo:warning=gpui_aros glue deferred to link time (SDK proto headers absent)"
        );
        return;
    }

    // CC / CFLAGS come from the workspace .cargo/config.toml (host clang, ELF
    // triple, large code model, x18 reserved, AROS SDK include paths).
    cc::Build::new()
        .file("c/gpui_aros_glue.c")
        .compile("gpui_aros_glue");
}
